//
//  Login.swift
//  PupTinder
//
//  Created by Hajra Mobashar on 11/9/19.
//  Copyright © 2019 ecs189e. All rights reserved.
//

import UIKit
import Firebase
import FirebaseDatabase

class Login: UIViewController {
    @IBOutlet weak var emailField: UITextField!
    @IBOutlet weak var passwordField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        /* At the moment, the following code serves for testing basic CRUD operations
           and is used for writing security rules. This code serves no purpose to the actual logic rn.
         
        // Get reference to Firestore Database
        let db = Firestore.firestore()
        
        // Adding a document, collection can exist but if not then it will be created, document IDs autogenerated
        /* db.collection("profiles").addDocument(data: ["picture":"file_path_string","name":"Tammy","breed":"Human","size":"S","bio":"I am a person","traits":"trait1","characteristics":"characteristic1"])
        */
        // Access document ID for a doc using document() method and access documentID property
        let newDoc = db.collection("profiles").document("named_doc")
        // setData() will replace data, use merge when append
        newDoc.setData(["picture":"file_path_string2","name":"Tammy2","breed":"Human2","size":"S2","bio":"I am a person 2","traits":["trait2"],"characteristics":["characteristic2"],"id":newDoc.documentID])
        // Delete document with delete() or delete field with updateData() with FieldValue.delete()
        // Read with getDocument, or getDocuments, or a subset using where()
        db.collection("profiles").document("named_doc").getDocument { (document, error) in
            if error == nil {
                // Check if document exists
                if let doc = document, doc.exists {
                    let documentData = doc.data()
                    print(documentData)
                }
            }
        }
        */
    }
    
    @IBAction func loginPressed() {
        guard let email = emailField.text, let password = passwordField.text else {
            return
        }
        Api.auth.login(email: email, password: password) { (error) in
            if error != nil {
                // TODO: Deal with the error
            } else {
                // TODO: Login was a success, so Segueway to the next screen!
                
                // This function is just for testing; remove after profile stuff is all working!
                self.testingFunction()
            }
        }
    }
    
    // This function is just for testing; remove after profile stuff is all working!
    func testingFunction() {
        Api.profiles.getProfileOf(uid: "HfPac5bFtmODf4YSZuuPZ76BBgH2") { (profile, error) in
            if let error = error {
                print(error)
            } else {
                guard let profile = profile else {return}
                print(profile.name, profile.bio, profile.breed, profile.size, profile.characteristics, profile.traits)
                let imageView = UIImageView(image: profile.picture)
                imageView.frame = CGRect(x: 0, y: 0, width: 100, height: 200)
                self.view.addSubview(imageView)
            }
        }
    }
    
    // This serves as a gateway to the Matches feature during development
    @IBAction func goToMatchesAndConversations() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let messengerVC = storyboard.instantiateViewController(withIdentifier: "MatchesAndConversations") as! MatchesAndConversations
        messengerVC.modalPresentationStyle = .fullScreen
        self.present(messengerVC, animated: true, completion: nil)
    }
    
}

